<?php /** @var $this IntegerNet_MagentoLocalized_Block_Frontend_Copyright */ ?>

<p>
    <?php $localeCode = Mage::app()->getLocale()->getLocaleCode() ?>
    <?php echo Mage::helper('magento_localized')->__('<a href="%s" target="_blank">%s</a> è un progetto della comunità Magento',
        'http://www.nr-apps.com/store/magento-it.html',
        'Magento IT'
    ) ?>
    <?php echo Mage::helper('magento_localized')->__('powered by') ?>
    <?php echo Mage::helper('magento_localized')->__('<a href="%s" target="_blank">Netresearch App Factory</a> &amp; <a href="%s" target="_blank">integer_net</a>',
        'http://www.nr-apps.com',
        'http://www.integer-net.com'
    ) ?>
</p>
